config/routes.rb
Rails.application.routes.draw do
  get 'board/index'
  root 'board#index'
  resources :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  validates_numericality_of :score, only_integer: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
  def index
    @passed = Student.all.where("score >= 72").order("score DESC")
    @failed = Student.all.where("score < 72").order("score DESC")
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @student = Student.new
  end

  def index
    @students = Student.all
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to @student
    else
      render 'new'
    end
  end

  def show
    @student = Student.find(params[:id])
  end


  private
    def student_params
      params.require(:student).permit(:name, :score)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/board/index.html.erb
<h1>Tablica ogłoszeń inFakt University</h1>
<h2>Lista osób zakwalifikowanych:</h2>
<% @passed.each do |student| %>
<strong><%= student.name %></strong> - ilość punktów: <%= student.score %><br/>
<% end %>
<h2>Lista osób niezakwalifikowanych:</h2>
<% @failed.each do |student| %>
<strong><%= student.name %></strong> - ilość punktów: <%= student.score %><br/>
<% end %>
<br/><br/>
<%= link_to 'Przejdź do admina dla dziekanatu >', students_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Students</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/index.html.erb
<h1>Lista studentów:</h1>
<%= link_to 'Dodaj studenta >', new_student_path %>
<br/><br/>
<table>
  <tr>
    <td>Student</td>
    <td>Wynik</td>
    <td>Podgląd:</td>
  </tr>

  <% @students.each do |student| %>
    <tr>
      <td><%= student.name %></td>
      <td><%= student.score %></td>
      <td><%= link_to 'Przejdź do profilu >', student_path(student) %></td>
    </tr>
  <% end %>
</table>
<br/><br/>
<%= link_to 'Powrót do listy zakwalifikowanych >', board_index_path %>

app/views/students/new.html.erb
<h1>Dodaj studenta do bazy:</h1>
<%= form_with scope: :student, url: students_path, local: true do |form| %>
<table>
  <tr><td>
    <%= form.label 'Imię studenta?' %><br>
    <%= form.text_field :name %>
  <td/>
  <td>
    <%= form.label 'Wynik studenta?' %><br>
    <%= form.text_area :score %>
  </td>
  <td>
    <%= form.submit 'Prześlij do dziekanatu' %>
  </td></tr>
</table>
<% end %>
<br/><br/>
<%= link_to 'Wyjdź bez zapisu >', students_path %>

app/views/students/show.html.erb
<h1>Podgląd studenta:</h1>
<table>
  <tr><td>
    <strong>Student:</strong>
  </td>
  <td>
    <strong>Wynik:</strong>
  </td></tr>
  <tr><td>
    <%= @student.name %>
  </td>
  <td>
    <%= @student.score %>
  </td></tr>
</table>
<br/>
<%= link_to 'Powrót do listy studentów >', students_path %>